apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-large
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        service: nginx
        app: nginx
    spec:
      nodeSelector:
        purpose: large-app
      tolerations:
      - key: "training"
        operator: "Equal"
        value: "cpu"
        effect: "NoSchedule"
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 500Mi