apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1

managedNodeGroups:
  - name: ng-small
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 20
    labels: 
      purpose: small-app
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/node-template/label/purpose: small-app
    iam:
      withAddonPolicies:
        autoScaler: true